name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZjE5NDcwMTItNGE0MS00NmFkLTliOTEtODA1ZjlkZDFkNzZhIiwidGVuYW50X2lkIjoiNDViYWY2OTEwODM1NTkyY2M1ZDZmMmEyMzAzMDM1NzY2MDVlZWZkY2EzMjUxOTkyMmJjODI3YzkyY2MxMjQxNSIsImludGVybmFsX3NlY3JldCI6IjQ2ZTYzZTFmLWYyOTgtNDkxOC05NTA3LWViNTMzM2E4MDUwMyJ9.wy7kOy9RcK0JHNN8X3qsGT_x3dIkdag4zu0Mb3g3GkM"
JWT_SECRET = "9839msm"


